ignore:
  # fast-xml-parser vulnerability
  - vulnerability: GHSA-37qj-frw5-hhjh
  # lodash vulnerabilities
  - vulnerability: GHSA-xxjr-mmjv-4gpg
  # @isaacs/brace-expansion vulnerability
  - vulnerability: GHSA-7h2j-956f-4vf2
  # busybox vulnerabilities
  - vulnerability: CVE-2025-60876
  # glob vulnerabilities
  - vulnerability: GHSA-5j98-mcp5-4vw2
  # tar vulnerabilities
  - vulnerability: GHSA-34x7-hfp2-rc4v
  - vulnerability: GHSA-r6q2-hw4h-h46w
  - vulnerability: GHSA-8qq5-rm4j-mr97
  - vulnerability: GHSA-29xp-372q-xqph
  # diff vulnerability
  - vulnerability: GHSA-73rr-hh4g-fpgx
  # npm vulnerability
  - vulnerability: GHSA-3966-f6p6-2qr9
# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
