ignore:
  # Remove this ignore after verifying CI builds fresh image
  - vulnerability: GHSA-5j98-mcp5-4vw2
    include-aliases: true
  - vulnerability: CVE-2025-60876
    reason: "No fixes available as of 2026-01-14 on Dockerfile base image 22.21.1-alpine3.23"
  - vulnerability: CVE-2026-22184
    reason: "No fixes available as of 2026-01-16 on Dockerfile base image 22.21.1-alpine3.23"

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
