ignore:
  # Remove this ignore after verifying CI builds fresh image
  - vulnerability: GHSA-5j98-mcp5-4vw2
    include-aliases: true
  - vulnerability: CVE-2025-60876
    reason: "No fixes available as of 2026-01-14 on Dockerfile base image 22.21.1-alpine3.23"
  - vulnerability: CVE-2026-22184
    reason: "No fixes available as of 2026-01-16 on Dockerfile base image 22.21.1-alpine3.23"
  - vulnerability: CVE-2026-28309
  - vulnerability: CVE-2025-59465
  - vulnerability: CVE-2025-55131
  - vulnerability: GHSA-r6q2-hw4h-h46w
  - vulnerability: GHSA-8qq5-rm4j-mr97
  - vulnerability: CVE-2025-55130
  - vulnerability: CVE-2026-21637
  - vulnerability: CVE-2025-59466
  - vulnerability: GHSA-xxjr-mmjv-4gpg
  # High severity vulnerabilities
  - vulnerability: CVE-2025-69420
    reason: "libcrypto3 3.3.5-r0, libssl3 3.3.5-r0"
  - vulnerability: GHSA-34x7-hfp2-rc4v
    reason: "tar 6.2.1, 7.4.3"
  # Medium severity vulnerabilities
  - vulnerability: CVE-2026-22796
    reason: "libcrypto3 3.3.5-r0, libssl3 3.3.5-r0"
  # libcrypto3 3.3.5-r0 / libssl3 3.3.5-r0: CVE-2025-15467
  - vulnerability: CVE-2025-15467
    reason: "libcrypto3 3.3.5-r0, libssl3 3.3.5-r0"
  # High severity vulnerabilities
  - vulnerability: GHSA-37qj-frw5-hhjh
    reason: "fast-xml-parser 4.5.3"
  - vulnerability: CVE-2025-69419
    reason: "libcrypto3 3.3.5-r0, libssl3 3.3.5-r0"
  - vulnerability: CVE-2025-69421
    reason: "libcrypto3 3.3.5-r0, libssl3 3.3.5-r0"
  # Medium severity vulnerabilities
  - vulnerability: CVE-2025-66199
    reason: "libcrypto3 3.3.5-r0, libssl3 3.3.5-r0"
  - vulnerability: CVE-2025-15468
    reason: "libcrypto3 3.3.5-r0, libssl3 3.3.5-r0"
  - vulnerability: CVE-2026-22795
    reason: "libcrypto3 3.3.5-r0, libssl3 3.3.5-r0"
  - vulnerability: GHSA-p5wg-g6qr-c7cg
    reason: "eslint 8.57.1"
  - vulnerability: CVE-2025-68160
    reason: "libcrypto3 3.3.5-r0, libssl3 3.3.5-r0"
  - vulnerability: CVE-2025-69418
    reason: "libcrypto3 3.3.5-r0, libssl3 3.3.5-r0"
  - vulnerability: GHSA-3966-f6p6-2qr9
# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
