version: "3.7"

services:
  ttk-mongodb:
    image: mongo:latest
    # Disable logging as it is far too verbose for debugging locally
    logging:
      driver: none
    ports:
      - "27017:27017"

networks:
  default:
    name: mojaloop-testing-toolkit


